[package]
name = "mp4san"
description = "An MP4 file sanitizer."
version = "0.1.0"
edition = "2021"

rust-version = "1.61.0"

repository = "https://github.com/privacyresearchgroup/mp4san"
license = "MIT"
categories = ["multimedia::video"]
keywords = ["mp4", "sanitizer", "video", "media"]

exclude = ["/.github", ".*"]

[dependencies]
bytes = "1.3.0"
log = "0.4.17"
mp4 = "0.12.0"
thiserror = "1.0.38"

[dev-dependencies]
env_logger = "0.10.0"
libflate = "1.2.0"
