[package]
name = "mp4san-test"
edition.workspace = true
version.workspace = true

publish = false

[features]
default = []
ffmpeg = ["dep:ac-ffmpeg", "dep:bindgen", "dep:cc", "dep:ffmpeg-sys-next"]
gpac = ["dep:bindgen", "dep:cc", "dep:pkg-config"]

[dependencies]
ac-ffmpeg = { version = "0.18.1", optional = true }
ffmpeg-sys-next = { version = "7.0.0", default-features = false, features = ["avformat"], optional = true }
log = "0.4.17"
thiserror = "1.0.40"

[build-dependencies]
bindgen = { version = "0.69.4", optional = true }
cc = { version = "1.0.79", optional = true }
pkg-config = { version = "0.3.26", optional = true }
